spring:
  application:
    name: ai-router
  profiles:
    active:
      - local
server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan:
        - com.xuanjia.airouter.controller

#http://localhost:8123/api/doc.html#/home
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
